### ISSUE TITLE
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by chellongCoder** [imbrook/ReactNativeQrReader#1]
I get an error on android when choice image from Photo. How to fix it? :( 
![image](https://user-images.githubusercontent.com/30166352/92988796-f8b68780-f4f8-11ea-9f6a-9ba89f19bd6f.png)

**Comment by imbrook** [comment]
Please run `react-native info` in your terminal and copy the results into your issue description

**Comment by chellongCoder** [comment]
@imbrook  my react-native info 
![image](https://user-images.githubusercontent.com/30166352/92988961-98c0e080-f4fa-11ea-9391-9c4e1395b330.png)

**Comment by chellongCoder** [comment]
@imbrook I try to fix it and I add `path: response.path` in `const source = {uri: response.uri, path: response.path};` because QRreader only read `path` of image on android, not `uri` .
![Screenshot_20200912-133019_ReactNativeQrReader](https://user-images.githubusercontent.com/30166352/92989158-58626200-f4fc-11ea-8657-052076730564.jpg)

**Comment by imbrook** [comment]
Good job👍
